### ISSUE TITLE
Ragnarok Online

### ISSUE THREAD

**Issue by Log1x** [kaisermann/ragnarok-scripts#1]
Man I miss RO...

I think making NPC's for eAthena with Lua was one of the first things I ever did programming-related.

Awesome you still have yours! Mine are long gone.

**Comment by kaisermann** [comment]
Wow, I didn't know it was Lua hahaha!

Man, RO was the best. Definitely miss those times ♥

I'm gonna upload two "editors" I made for Ragnarok files in VB.net. Unfortunately I only have the executables :( the source code is no where to be found

**Comment by kaisermann** [comment]
I don't know if you ever heard of the "Bros editor"

**Comment by Log1x** [comment]
Not "Bros editor" but have heard of [browedit](https://github.com/Borf/browedit).

I remember spending months as a kid making the "perfect" private server but never having any money to run it. lol -- I also think it was TXT based instead of SQL because I had no idea what I was really doing.

My last server that I was serious on was XiLeRO -- but I don't even know how long ago. I know it was before the third jobs back when LK's could spam a million spiral pierces a second. 😀
